version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "22:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.13.9
  - dependency-name: "@babel/core"
    versions:
    - 7.13.8
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
    - 7.21.0
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.4.0
    - 7.5.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: eslint-plugin-html
    versions:
    - 6.1.1
